2025-04-12 23:24:39,104 INFO Watching for file changes with StatReloader
2025-04-12 23:30:56,258 INFO Watching for file changes with StatReloader
2025-04-13 19:49:33,998 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/NewsPaper/settings.py changed, reloading.
2025-04-13 19:49:34,878 INFO Watching for file changes with StatReloader
2025-04-13 22:47:39,239 INFO Watching for file changes with StatReloader
2025-04-13 22:47:48,042 WARNING Not Found: /favicon.ico
2025-04-13 22:47:48,042 WARNING Not Found: /favicon.ico
2025-04-14 21:59:17,697 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/NewsPaper/settings.py changed, reloading.
2025-04-14 21:59:18,599 INFO Watching for file changes with StatReloader
2025-04-14 22:03:31,423 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/NewsPaper/settings.py changed, reloading.
2025-04-14 22:03:32,239 INFO Watching for file changes with StatReloader
2025-04-14 22:24:19,486 INFO Watching for file changes with StatReloader
2025-04-14 22:24:40,279 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 280, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:24:40,279 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 280, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:24:40,298 ERROR "GET /admin/news/comment/ HTTP/1.1" 500 7527
2025-04-14 22:24:59,858 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 280, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:24:59,858 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 280, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:24:59,864 ERROR "GET /admin/news/comment/ HTTP/1.1" 500 7527
2025-04-14 22:25:07,368 ERROR Internal Server Error: /admin/news/post/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:25:07,368 ERROR Internal Server Error: /admin/news/post/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:25:07,374 ERROR "GET /admin/news/post/ HTTP/1.1" 500 7527
2025-04-14 22:30:03,374 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py changed, reloading.
2025-04-14 22:30:04,369 INFO Watching for file changes with StatReloader
2025-04-14 22:31:24,947 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py changed, reloading.
2025-04-14 22:31:25,902 INFO Watching for file changes with StatReloader
2025-04-14 22:33:18,120 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py changed, reloading.
2025-04-14 22:33:18,964 INFO Watching for file changes with StatReloader
2025-04-14 22:35:00,883 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py changed, reloading.
2025-04-14 22:35:01,772 INFO Watching for file changes with StatReloader
2025-04-14 22:35:18,147 INFO Watching for file changes with StatReloader
2025-04-14 22:35:49,799 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 298, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:35:49,799 ERROR Internal Server Error: /admin/news/comment/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Comment has no field named 'name_post'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 239, in __get__
    rel_obj = self.field.get_cached_value(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/mixins.py", line 37, in get_cached_value
    return instance._state.fields_cache[self.cache_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'post_comment'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/utils.py", line 299, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "/home/igoriusha/MyProject/Portal_News/NewsPaper/news/admin.py", line 298, in name_post
    return obj.preview(obj.post_comment.title_post)
                       ^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 257, in __get__
    rel_obj = self.get_object(instance)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/fields/related_descriptors.py", line 220, in get_object
    return qs.get(self.field.get_reverse_related_filter(instance))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 645, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:35:49,805 ERROR "GET /admin/news/comment/ HTTP/1.1" 500 7527
2025-04-14 22:35:56,780 ERROR Internal Server Error: /admin/news/post/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:35:56,780 ERROR Internal Server Error: /admin/news/post/
Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 718, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 241, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/utils/decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2140, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 382, in __len__
    self._fetch_all()
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 1928, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1574, in execute_sql
    cursor.execute(sql, params)
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/igoriusha/.virtualenvs/.venv/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column news_post.image does not exist
LINE 1: ..._post"."time_in_post", "news_post"."rating_post", "news_post...
                                                             ^

2025-04-14 22:35:56,784 ERROR "GET /admin/news/post/ HTTP/1.1" 500 7527
2025-04-14 22:42:37,767 INFO Watching for file changes with StatReloader
2025-04-14 22:48:03,745 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/models.py changed, reloading.
2025-04-14 22:48:04,676 INFO Watching for file changes with StatReloader
2025-04-14 22:52:16,591 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/models.py changed, reloading.
2025-04-14 22:52:17,484 INFO Watching for file changes with StatReloader
2025-04-14 23:08:09,855 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/models.py changed, reloading.
2025-04-14 23:08:10,735 INFO Watching for file changes with StatReloader
2025-04-14 23:22:28,312 INFO Watching for file changes with StatReloader
2025-04-14 23:28:53,854 WARNING Not Found: /favicon.ico
2025-04-14 23:28:53,854 WARNING Not Found: /favicon.ico
2025-04-14 23:31:59,970 WARNING Not Found: /favicon.ico
2025-04-14 23:31:59,970 WARNING Not Found: /favicon.ico
2025-04-14 23:33:39,427 WARNING Not Found: /favicon.ico
2025-04-14 23:33:39,427 WARNING Not Found: /favicon.ico
2025-04-14 23:36:30,683 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-14 23:36:31,598 INFO Watching for file changes with StatReloader
2025-04-14 23:36:56,453 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-14 23:36:57,244 INFO Watching for file changes with StatReloader
2025-04-14 23:37:16,918 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-14 23:37:17,791 INFO Watching for file changes with StatReloader
2025-04-14 23:38:42,269 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-14 23:38:43,115 INFO Watching for file changes with StatReloader
2025-04-14 23:38:58,097 WARNING Not Found: /favicon.ico
2025-04-14 23:38:58,097 WARNING Not Found: /favicon.ico
2025-04-14 23:39:54,301 WARNING Not Found: /favicon.ico
2025-04-14 23:39:54,301 WARNING Not Found: /favicon.ico
2025-04-14 23:57:36,171 WARNING Not Found: /favicon.ico
2025-04-14 23:57:36,171 WARNING Not Found: /favicon.ico
2025-04-14 23:58:02,578 WARNING Not Found: /favicon.ico
2025-04-14 23:58:02,578 WARNING Not Found: /favicon.ico
2025-04-14 23:58:58,779 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-14 23:58:59,616 INFO Watching for file changes with StatReloader
2025-04-14 23:59:18,172 WARNING Not Found: /favicon.ico
2025-04-14 23:59:18,172 WARNING Not Found: /favicon.ico
2025-04-14 23:59:55,042 WARNING Not Found: /favicon.ico
2025-04-14 23:59:55,042 WARNING Not Found: /favicon.ico
2025-04-15 00:07:24,388 WARNING Not Found: /favicon.ico
2025-04-15 00:07:24,388 WARNING Not Found: /favicon.ico
2025-04-15 00:09:23,104 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:09:23,104 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:09:23,358 WARNING Not Found: /favicon.ico
2025-04-15 00:09:23,358 WARNING Not Found: /favicon.ico
2025-04-15 00:10:42,711 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-15 00:10:43,525 INFO Watching for file changes with StatReloader
2025-04-15 00:10:51,905 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:10:51,905 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:10:52,065 WARNING Not Found: /favicon.ico
2025-04-15 00:10:52,065 WARNING Not Found: /favicon.ico
2025-04-15 00:13:33,563 WARNING Not Found: /favicon.ico
2025-04-15 00:13:33,563 WARNING Not Found: /favicon.ico
2025-04-15 00:17:11,780 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/urls.py changed, reloading.
2025-04-15 00:17:12,610 INFO Watching for file changes with StatReloader
2025-04-15 00:17:49,852 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/NewsPaper/urls.py changed, reloading.
2025-04-15 00:17:50,722 INFO Watching for file changes with StatReloader
2025-04-15 00:20:25,106 INFO Watching for file changes with StatReloader
2025-04-15 00:22:23,839 WARNING Not Found: /favicon.ico
2025-04-15 00:22:23,839 WARNING Not Found: /favicon.ico
2025-04-15 00:25:36,948 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:25:36,948 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:25:37,098 WARNING Not Found: /favicon.ico
2025-04-15 00:25:37,098 WARNING Not Found: /favicon.ico
2025-04-15 00:40:42,059 INFO Watching for file changes with StatReloader
2025-04-15 00:40:56,160 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:40:56,160 WARNING Not Found: /articles/Не самые популярные методы Django ORM.
2025-04-15 00:40:56,309 WARNING Not Found: /favicon.ico
2025-04-15 00:40:56,309 WARNING Not Found: /favicon.ico
2025-04-15 00:41:59,062 WARNING Not Found: /favicon.ico
2025-04-15 00:41:59,062 WARNING Not Found: /favicon.ico
2025-04-15 00:42:15,158 WARNING Not Found: /favicon.ico
2025-04-15 00:42:15,158 WARNING Not Found: /favicon.ico
2025-04-15 00:49:54,484 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/NewsPaper/settings.py changed, reloading.
2025-06-09 13:14:56,159 INFO Watching for file changes with StatReloader
2025-06-09 13:17:17,170 INFO /home/igoriusha/MyProject/Portal_News/NewsPaper/news/views.py changed, reloading.
2025-06-09 13:17:18,084 INFO Watching for file changes with StatReloader
2025-06-09 13:19:22,051 WARNING Not Found: /favicon.ico
2025-06-09 13:19:22,051 WARNING Not Found: /favicon.ico
2025-06-09 13:19:33,152 WARNING Not Found: /favicon.ico
2025-06-09 13:19:33,152 WARNING Not Found: /favicon.ico
2025-06-09 13:19:45,050 WARNING Not Found: /favicon.ico
2025-06-09 13:19:45,050 WARNING Not Found: /favicon.ico
